---
- include_vars: "{{ ansible_os_family }}-vars.yml"
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Start ldap service
  service:
    name: slapd
    state: started
    enabled: true

- name: Register encripted password
  command: slappasswd -s "{{ ldap_auth.bind_pw }}"
  register: ldap_encripted_password

- name: Copy db templates
  template:
    src: db.ldif
    dest: /tmp

- name: Load db template into ldap
  command: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/db.ldif

- name: Load some schemas (ignoring duplicate entries error for idempotence)
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{ schema_path }}/{{ item }}"
  register: ldap_result_code
  failed_when: ldap_result_code.rc not in [0,80]
  changed_when: ldap_result_code.rc not in [0,80]
  with_items:
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif

#- include: OLD-DIT.yml
#  tags: old_dit

- import_tasks: DIT.yml
  tags: dit

- name: Restart ldap service
  service:
    name: slapd
    state: restarted
